### PR TITLE
use camel case for nexus metadata

### PR DESCRIPTION
**Pull request by AurelienJaquier**
We'll have to force nexus team to update all nexus resources we have uploaded for OBP with camel case metadata if we merge this

### CODE REVIEW

**Comment by ilkilic** [comment]
Could we consider supporting both naming conventions? I believe accommodating both should be feasible in bpemnexus, no?

**Comment by AurelienJaquier** [comment]
Sure, I'll see if it can be implemented

**Review by ilkilic — APPROVED** [review]
Thank you! looks good here by the way

**Comment by darshanmandge** [comment]
> Could we consider supporting both naming conventions?

@AurelienJaquier Are we going to do this? It might save us a lot of time. Will this PR need changes for keeping this backcompatibility?

**Comment by AurelienJaquier** [comment]
I'm looking into it, I'll probably have to update this PR also

**Pull request merged**
